services:
  fastapi-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-auto-signin-agent
    ports:
      - "3978:3978"
    environment:
      # FastAPI Configuration
      - HOST=0.0.0.0
      - PORT=3978
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3978/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
